# memes (common stuff, mostly lists)
# HyperBot++
# Licensed under the DBBPL
# (C) 2021 githubcatw

from userbot.sysutils.registration import register_module_desc, register_module_info
from os.path import basename

VERSION = "2021.8"

ZALG_LIST = [[
    "̖",
    " ̗",
    " ̘",
    " ̙",
    " ̜",
    " ̝",
    " ̞",
    " ̟",
    " ̠",
    " ̤",
    " ̥",
    " ̦",
    " ̩",
    " ̪",
    " ̫",
    " ̬",
    " ̭",
    " ̮",
    " ̯",
    " ̰",
    " ̱",
    " ̲",
    " ̳",
    " ̹",
    " ̺",
    " ̻",
    " ̼",
    " ͅ",
    " ͇",
    " ͈",
    " ͉",
    " ͍",
    " ͎",
    " ͓",
    " ͔",
    " ͕",
    " ͖",
    " ͙",
    " ͚",
    " ", ],
    [
        " ̍",
        " ̎",
        " ̄",
        " ̅",
        " ̿",
        " ̑",
        " ̆",
        " ̐",
        " ͒",
        " ͗",
        " ͑",
        " ̇",
        " ̈",
        " ̊",
        " ͂",
        " ̓",
        " ̈́",
        " ͊",
        " ͋",
        " ͌",
        " ̃",
        " ̂",
        " ̌",
        " ͐",
        " ́",
        " ̋",
        " ̏",
        " ̽",
        " ̉",
        " ͣ",
        " ͤ",
        " ͥ",
        " ͦ",
        " ͧ",
        " ͨ",
        " ͩ",
        " ͪ",
        " ͫ",
        " ͬ",
        " ͭ",
        " ͮ",
        " ͯ",
        " ̾",
        " ͛",
        " ͆",
        " ̚",
    ],
    [
        " ̕",
        " ̛",
        " ̀",
        " ́",
        " ͘",
        " ̡",
        " ̢",
        " ̧",
        " ̨",
        " ̴",
        " ̵",
        " ̶",
        " ͜",
        " ͝",
        " ͞",
        " ͟",
        " ͠",
        " ͢",
        " ̸",
        " ̷",
        " ͡", ]]

EMOJIS = [
    "😂",
    "😂",
    "👌",
    "✌",
    "💞",
    "👍",
    "👌",
    "💯",
    "🎶",
    "👀",
    "😂",
    "👓",
    "👏",
    "👐",
    "🍕",
    "💥",
    "🍴",
    "💦",
    "💦",
    "🍑",
    "🍆",
    "😩",
    "😏",
    "👉👌",
    "👀",
    "👅",
    "😩",
    "🚰"]

PUNCH_TEMPLATES = [
    "{punches} {victim} to assert dominance.",
    "{punches} {victim} to see if they shut the fuck up for once.",
    "{punches} {victim} because they were asking for it.",
    "It's over {victim}, they have the high ground.",
    "performs a superman punch on {victim}, {victim} is rekt now.",
    "makes {victim} go on tiktok. {victim} gets cancer. ",
    "kills off {victim} with a T.K.O",
    "attacks {victim} with a billiard cue. A bloody mess.",
    "disintegrates {victim} with a MG.",
    "A hit and run over {victim} performed by me",
    "punches {victim} into the throat. Warning, choking hazard!",
    "drops a piano on top of {victim}. A harmonical death.",
    "throws rocks at {victim}",
    "forces {victim} to drink chlorox. What a painful death.",
    "got sliced in half by {victim}'s katana.",
    "makes {victim} fall on their sword. A stabby death lol.",
    "kangs {victim} 's life energy away.",
    "shoots {victim} into a million pieces. Hasta la vista baby.",
    "drops the frigde on {victim}. Beware of crushing.",
    "engages a guerilla tactic on {victim}",
    "ignites {victim} into flames. IT'S LIT FAM.",
    "pulls a loaded 12 gauge on {victim}.",
    "throws a Galaxy Note7 into {victim}'s general direction. A bombing massacre.",
    "walks with {victim} to the end of the world, then pushes him over the edge.",
    "performs a Stabby McStabby on {victim} with a butterfly.",
    "cuts {victim}'s neck off with a machete. A blood bath.",
    "secretly fills in {victim}'s cup with Belle Delphine's Gamer Girl Bathwater instead of water. Highly contagious herpes.",
    "is tea cupping on {victim} after a 1v1, to assert their dominance.",
    "asks for {victim}'s last words. {victim} is ded now.",
    "lets {victim} know their position.",
    "makes {victim} to his slave. What is your bidding? My Master.",
    "forces {victim} to commit suicide.",
    "shouts 'it's garbage day' at {victim}.",
    "throws his axe at {victim}.",
    "is now {victim}'s grim reaper.",
    "slappety slap's {victim}.",
    "ends the party.",
    "will never know what hit them.",
    "breaks {victim}'s neck like a kitkat.",
    "flings knives at {victim}.",
    "gangs {victim} in a drive by.",
    "Thanks to my airstrike, {victim} is no more.",
    "waterboard's {victim}.",
    "hangs {victim} upside down.",
    "breaks (victim)'s skull with a PS4.",
    "throws Xbox controller batteries at {victim}'s face.",
    "shouts 'Look at me, I'm the Captain now.' at {victim}.",
    "puts {victim} in their place.",
    "poisons {victim}'s meal, it was their last meal.",
    "burns {victim} into ashes.",
    "bites in the dust.",
    "stabs {victim} in their back, what a way to die.",
    "uses {victim} to play Fruit Ninja.",
    "blueballs {victim}.",
    "makes the fool die a fool's death.",
    "orders Agent 47 on {victim}'s ass.",
    "gets struck by a lightning. Warning, high tension.",
    "breaks all of {victim}'s bones.",
    "Someone save {victim} because I is about to murder them.",
    "throws {victim} into a volcano.",
    "chokes {victim} through the force.",
    "throws their lightsaber at {victim}.",
    "orders a full broadside on {victim}.",
    "deploys the garrison on {victim}.",
    "lets freeze {victim} to death.",
    "throws {victim} across the room by the force.",
    "makes {victim} go crazy by high pitch sounds.",
    "rolls over {victim} with a Panzerkampfwagen VI Tiger.",
    "blows {victim} up with a bazooka.",
    "plays Sniper Elite with {victim} as the target.",
    "yeets {victim}'s ass.)",
    "puts a grenade in {victim}'s hood.",
    "throws an iPhone 11 Pro Max at {victim}'s face.",
    "throws a Galaxy S20 Ultra 5G at {victim}'s face.",
    "draws a dick on {victim}'s forehead.",
    "cuts open {victim}'s throat. Very bloody.",
    "shoots {victim} to dust with a {gun}.",
    "lands a headshot on {victim} with their {gun}.",
    "shoots down {victim} with a {gun}."
    "stashes a Glock."
    "lures {victim} on a minefield.",
    "wins over {victim} in a western 1v1.",
    "plays robbers and gendarmes with {victim}.",
    "tries their new {gun} on {victim}.",
    "steals all of {victim}'s money. Now they're broke af.",
    "drops a TV on {victim}.",
    "throws their Apple TV at {victim}.",
    "hijacks {victim}'s ship.",
    "makes {victim} sign their death certificate.",
    "kangs everything what {victim} owns.",
    "manipulates {victim}'s breaks.",
    "ties {victim} down on the train tracks.",
    "chops {victim}'s arm off with their lightsaber.",
]

PUNCH = [
    "punches",
    "RKOs",
    "smashes the skull of",
    "throws a pipe wrench at",
]
GUN = [
    "AK-47",
    "M1911",
    "M1928 Thommy",
    "M1 Abrams tank",
    "M16",
    "M1 Garand",
    "Avtomat Federov",
    "CHAUCHAT",
    "Avtomat Kalashnikov",
    "M1928.A1 Thompson",
    "M1911.A1",
    ".45 ACP",
    "Colt 1911",
    "Ithaca 1911",
    "9mm Luger",
    "UZI",
    "Galil Ace",
    "StG 44",
    "MP 38",
    "MP 40",
    "StG 40",
    "Model 27",
    ".44 Magnum",
    "MP 28",
    "M8 con Tromboncino",
    "STEN",
    "M3 Carbine",
    "M3 Grease Gun",
    "M2 Carbine",
    "Kar98k",
    "Maschinengewehr 34",
    "Maschinengewehr 42",
    "HK MP5",
    "MP5",
    "Heckler & Koch G36 C",
    "Heckler & Koch G36",
    "HK G36 C",
    "HK G36",
    "SCAR FN",
    "Glock 17",
    "Glock 18",
    "Glock 19",
    "Glock 20",
    "Glock 21",
    "Glock 22",
    "Glock 23",
    "Glock 30",
    "Glock 40",
    "Glock 42",
    "Glock 44",
    "Glock 45",
    "Glock 48",
    "M1941 Johnson Rifle",
    "M1941 Johnson",
    "Nambu Type 2A",
    "Type 100",
    "FLAK",
    "Type 99 Arisaka",
    "Ribeyrolles 1918",
    "Panzerbüchse 39"
    "Panzerbüchse Boys",
    "M1897",
    "12 Gauge Automatic",
    "Drilling M30",
    "PPsh",
    "Sturmgewehr 40",
    "Sturmgewehr 44",
    "Maschinenpistole 38",
    "Maschinenpistole 40",
    "AK-44S",
    "Colt 44 Magnum",
    "AA-12",
    "ACR",
    "Desert Eagle",
    ".50",
    "FAL",
    "M-200 Intervention",
    "M249 Saw",
    "M4A1",
    "FN P90",
    "Suomi KP31",
    "PDR",
    "PPsh-41",
    "SPAS-12",
    "Beretta M9",
    "SCAR-H",
    "Thompson M1921",
    "M1921",
    "HK USP",
    "Heckler & Koch USP",
    "XD-9",
    "1887 Mare S Leg",
    "M1912 Repetierpistole",
    "Ruby",
    "AK-45 Korovin",
    "AK-45 KOROVIN",
    "AVTOMAT KALASHNIKOV 45 KOROVIN",
    "AK-74",
    "Avtomat Kalashnikov 74",
    "Avtomat Kalashnikov 47",
    "AR-70",
    "Fliegerfaust",
    "PIAT",
    "M1A1 Bazooka",
    "Bazooka",
    "Bangalore",
    "AK-5C",
    "Avtomat Kalashnikov 5C",
    "Ameli",
    "Welgun",
    "Coach Gun",
    "HK 417",
    "Heckler & Koch 417",
    "Honey Badger",
    "Sjögren",
    "M1898",
    "Krag-Jørgensen",
    "Krag-Jørgensen M1898",
    "Maschinengewehr 15",
    "MG 15",
    "Madsen MG",
    "Panzerfaust",
    "PANZERFAUST",
    "PANZERABWEHRMINE",
    "Panzerabwehrmine",
    "SCAR PDW",
    "XD59",
    "Model 37 shotgun",]

SLAP_TEMPLATES = [
    "{hits} {victim} with **{item}**. {emoji}",
    "{hits} {victim} in the face with **{item}**. {emoji}",
    "{hits} {victim} around a bit with **{item}**. {emoji}",
    "{throws} **{item}** at {victim}. {emoji}",
    "grabs **{item}** and {throws} it at {victim}'s face. {emoji}",
    "launches **{item}** in {victim}'s general direction. {emoji}",
    "starts slapping {victim} silly with **{item}**. {emoji}",
    "pins {victim} down and repeatedly {hits} them with **{item}**. {emoji}",
    "grabs up **{item}** and {hits} {victim} with it. {emoji}",
    "ties {victim} to a chair and {throws} **{item}** at them. {emoji}"]

ITEMS = (
    "a Pixel 5",
    "2021.8",
    "a Pixel 4 bezel",
    "a Galaxy S20 FE",
    "One UI 3",
    "a Galaxy A02s",
    "an iPhone",
    "end of support",
    "an incomplete API",
    "an Exynos 990",
    "a Xiaomi",
    "a Huawei",
    "a Vivo",
    "the Death Star",
    "a Redmi",
    "a Redmi Note 10 Pro Max",
    "a Redmi Note 8",
    "RetardOS",
    "PE for sunfish",
    "bootloader unlock",
    "a potion of retardation",
    "SafetyNet failing",
    "basic attestation",
    "a Galaxy A02s",
    "a brick",
    "official TWRP",
    "bootloops",
    "an ETA request",
    "a piece of wood",
    "KG prenormal",
    "Android 12 beta",
    "Android 11 for Mi A3",
    "a free 1000% legit no virus free download link",
    "a permanently locked bootloader",
    "HWC fix",
    "a cracked APK",
    "sudo",
    "official pixel room",
    "DeX port",
    "a Nokia 3310",
    "a Samsung J5 2017",
    "a Samsung S10+",
    "an iPhone XS MAX",
    "a Note 9",
    "a Note 10+",
    "knox 0x0",
    "OneUI 2.0",
    "TwoUI 1.0",
    "Secure Folder",
    "Samsung Pay",
    "prenormal RMM state",
    "prenormal KG state",
    "a locked bootloader",
    "payment lock",
    "stock ROM",
    "good rom",
    "best rom",
    "Good Lock apps",
    "Q port",
    "R port",
    "Pie port",
    "8.1 port",
    "Pie OTA",
    "Q OTA",
    "LineageOS 16",
    "LineageOS 17",
    "a bugless rom",
    "a kernel",
    "a kernal",
    "a karnal",
    "a karnel",
    "official TWRP",
    "VOLTE",
    "BOLTE",
    "a kanged ROM",
    "an antikang",
    "audio fix",
    "hwcomposer fix",
    "mic fix",
    "random reboots",
    "bootloops",
    "unfiltered logs",
    "a keylogger",
    "120 FPS",
    "168h uptime",
    "a paypal link",
    "treble support",
    "EVO-X gsi",
    "Q gsi",
    "Q beta",
    "a ROM Control",
    "a hamburger",
    "a cheeseburger",
    "a Big-Mac")

THROW = [
    "throws",
    "flings",
    "chucks",
    "hurls"]

HIT = [
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "spanks",
    "bashes"]

EMOJI = (
    "\U0001F923",
    "\U0001F602",
    "\U0001F922",
    "\U0001F605",
    "\U0001F606",
    "\U0001F609",
    "\U0001F60E",
    "\U0001F929",
    "\U0001F623",
    "\U0001F973",
    "\U0001F9D0",
    "\U0001F632")
    
FACEREACTS = [
    "ʘ‿ʘ",
    "ヾ(-_- )ゞ",
    "(っ˘ڡ˘ς)",
    "(´ж｀ς)",
    "( ಠ ʖ̯ ಠ)",
    "(° ͜ʖ͡°)╭∩╮",
    "(ᵟຶ︵ ᵟຶ)",
    "(งツ)ว",
    "ʚ(•｀",
    "(っ▀¯▀)つ",
    "(◠﹏◠)",
    "( ͡ಠ ʖ̯ ͡ಠ)",
    "( ఠ ͟ʖ ఠ)",
    "(∩｀-´)⊃━☆ﾟ.*･｡ﾟ",
    "(⊃｡•́‿•̀｡)⊃",
    "(._.)",
    "{•̃_•̃}",
    "(ᵔᴥᵔ)",
    "♨_♨",
    "⥀.⥀",
    "ح˚௰˚づ ",
    "(҂◡_◡)",
    "ƪ(ړײ)‎ƪ​​",
    "(っ•́｡•́)♪♬",
    "◖ᵔᴥᵔ◗ ♪ ♫ ",
    "(☞ﾟヮﾟ)☞",
    "[¬º-°]¬",
    "(Ծ‸ Ծ)",
    "(•̀ᴗ•́)و ̑̑",
    "ヾ(´〇`)ﾉ♪♪♪",
    "(ง'̀-'́)ง",
    "ლ(•́•́ლ)",
    "ʕ •́؈•̀ ₎",
    "♪♪ ヽ(ˇ∀ˇ )ゞ",
    "щ（ﾟДﾟщ）",
    "( ˇ෴ˇ )",
    "눈_눈",
    "(๑•́ ₃ •̀๑) ",
    "( ˘ ³˘)♥ ",
    "ԅ(≖‿≖ԅ)",
    "♥‿♥",
    "◔_◔",
    "⁽⁽ଘ( ˊᵕˋ )ଓ⁾⁾",
    "乁( ◔ ౪◔)「      ┑(￣Д ￣)┍",
    "( ఠൠఠ )ﾉ",
    "٩(๏_๏)۶",
    "┌(ㆆ㉨ㆆ)ʃ",
    "ఠ_ఠ",
    "(づ｡◕‿‿◕｡)づ",
    "(ノಠ ∩ಠ)ノ彡( \\o°o)\\",
    "“ヽ(´▽｀)ノ”",
    "༼ ༎ຶ ෴ ༎ຶ༽",
    "｡ﾟ( ﾟஇ‸இﾟ)ﾟ｡",
    "(づ￣ ³￣)づ",
    "(⊙.☉)7",
    "ᕕ( ᐛ )ᕗ",
    "t(-_-t)",
    "(ಥ⌣ಥ)",
    "ヽ༼ ಠ益ಠ ༽ﾉ",
    "༼∵༽ ༼⍨༽ ༼⍢༽ ༼⍤༽",
    "ミ●﹏☉ミ",
    "(⊙_◎)",
    "¿ⓧ_ⓧﮌ",
    "ಠ_ಠ",
    "(´･_･`)",
    "ᕦ(ò_óˇ)ᕤ",
    "⊙﹏⊙",
    "(╯°□°）╯︵ ┻━┻",
    r"¯\_(⊙︿⊙)_/¯",
    "٩◔̯◔۶",
    "°‿‿°",
    "ᕙ(⇀‸↼‶)ᕗ",
    "⊂(◉‿◉)つ",
    "V•ᴥ•V",
    "q(❂‿❂)p",
    "ಥ_ಥ",
    "ฅ^•ﻌ•^ฅ",
    "ಥ﹏ಥ",
    "（ ^_^）o自自o（^_^ ）",
    "ಠ‿ಠ",
    "ヽ(´▽`)/",
    "ᵒᴥᵒ#",
    "( ͡° ͜ʖ ͡°)",
    "┬─┬﻿ ノ( ゜-゜ノ)",
    "ヽ(´ー｀)ノ",
    "☜(⌒▽⌒)☞",
    "ε=ε=ε=┌(;*´Д`)ﾉ",
    "(╬ ಠ益ಠ)",
    "┬─┬⃰͡ (ᵔᵕᵔ͜ )",
    "┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻",
    r"¯\_(ツ)_/¯",
    "ʕᵔᴥᵔʔ",
    "(`･ω･´)",
    "ʕ•ᴥ•ʔ",
    "ლ(｀ー´ლ)",
    "ʕʘ̅͜ʘ̅ʔ",
    "（　ﾟДﾟ）",
    r"¯\(°_o)/¯",
    "(｡◕‿◕｡)",
]

SHGS = [
    "┐(´д｀)┌",
    "┐(´～｀)┌",
    "┐(´ー｀)┌",
    "┐(￣ヘ￣)┌",
    "╮(╯∀╰)╭",
    "╮(╯_╰)╭",
    "┐(´д`)┌",
    "┐(´∀｀)┌",
    "ʅ(́◡◝)ʃ",
    "┐(ﾟ～ﾟ)┌",
    "┐('д')┌",
    "┐(‘～`;)┌",
    "ヘ(´－｀;)ヘ",
    "┐( -“-)┌",
    "ʅ（´◔౪◔）ʃ",
    "ヽ(゜～゜o)ノ",
    "ヽ(~～~ )ノ",
    "┐(~ー~;)┌",
    "┐(-。ー;)┌",
    r"¯\_(ツ)_/¯",
    r"¯\_(⊙_ʖ⊙)_/¯",
    r"¯\_༼ ಥ ‿ ಥ ༽_/¯",
    "乁( ⁰͡  Ĺ̯ ⁰͡ ) ㄏ",
]

CRI = [
    "أ‿أ",
    "╥﹏╥",
    "(;﹏;)",
    "(ToT)",
    "(┳Д┳)",
    "(ಥ﹏ಥ)",
    "（；へ：）",
    "(T＿T)",
    "（πーπ）",
    "(Ｔ▽Ｔ)",
    "(⋟﹏⋞)",
    "（ｉДｉ）",
    "(´Д⊂ヽ",
    "(;Д;)",
    "（>﹏<）",
    "(TдT)",
    "(つ﹏⊂)",
    "༼☯﹏☯༽",
    "(ノ﹏ヽ)",
    "(ノAヽ)",
    "(╥_╥)",
    "(T⌓T)",
    "(༎ຶ⌑༎ຶ)",
    "(☍﹏⁰)｡",
    "(ಥ_ʖಥ)",
    "(つд⊂)",
    "(≖͞_≖̥)",
    "(இ﹏இ`｡)",
    "༼ಢ_ಢ༽",
    "༼ ༎ຶ ෴ ༎ຶ༽",
]

DOUBT = [
    "Doubt",
    "Are you sure?",
    "Sure about that?",
    "Really?",
]

register_module_desc("Memes! Contains data for the other meme modules and can't be used.")
register_module_info(
    name="Memes - common data",
    authors="githubcatw, @BottomTextBot, Haklerman",
    version=VERSION
)